#!/usr/bin/env python3

# MODULES
import json
import time
import subprocess
import auth
import functions

# AUTH
tickets_url = auth.url
user = auth.email + '/token'
token = auth.key

local_new_tickets = functions.get_tickets(tickets_url, user, token) # sets intital local ticket count to match that of Zendesk

while True:
    url = tickets_url # resets url for looping
    zendesk_new_tickets = functions.get_tickets(url, user, token) # gets current ticket count from Zendesk

    # Compare number of New Tickets locally stored to number of New Tickets in Zendesk
    if local_new_tickets < zendesk_new_tickets:
        print('LOUD MUSIC') #  Status Cue
        subprocess.call(['afplay', 'you_suffer.mp3'])
        local_new_tickets = zendesk_new_tickets # Sets Local Ticket Counter equal to Zendesk
    else:
        print('waiting for new ticket...') # Status Cue

    time.sleep(5)
